apiVersion: batch/v1
kind: Job
metadata:
  name: drp-product-url-crawler
spec:
  backoffLimit: 1000
  parallelism: 1 # Number of Pods start together with Job
  template:
    spec:
      containers:
        - name: drp-product-url-crawler
          image: $IMAGE
          imagePullPolicy: Never
          command: ["python3", "windml/train_net.py"]
          args: ["--config", "configs/config.test.yaml"]
          resources:
            limits:
              cpu: 2
              ephemeral-storage: 1Gi
              memory: 4Gi
            requests:
              cpu: 1
              ephemeral-storage: 1Gi
              memory: 2Gi
      restartPolicy: "Never"