---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wind-estimator-deployment
  labels:
    app: wind-estimator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wind-estimator
  template:
    metadata:
      labels:
        app: wind-estimator
    spec:
      containers:
        - name: wind-estimator
          image: wml
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: wind-estimator-secrets
                  key: db_root_password
            - name: db_name
              value: wind-estimator

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: wind-estimator
  type: LoadBalancer