---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wind-estimator-deployment
  labels:
    app: wind-estimator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wind-estimator
  template:
    metadata:
      labels:
        app: wind-estimator
    spec:
      containers:
        - name: wind-estimator
          image: $IMAGE
          imagePullPolicy: Never
          command: ["uvicorn", "windml.app:app"]
          args: ["--reload", "--host", "0.0.0.0"]
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 1
              ephemeral-storage: 1Gi
              memory: 2Gi
            requests:
              cpu: 1
              ephemeral-storage: 1Gi
              memory: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: wind-estimator-service
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8000
  selector:
    app: wind-estimator
  type: LoadBalancer